#!/usr/bin/env python
import sys

test_modules = [
    'cryptutil',
    'association',
    'storetest',
    'trustroot',
    'linkparse',
    'oidutil',
    'kvform',
    'consumer',
    'fetchers',
    'dh',
    'server',
    ]

failed = []
for module_name in test_modules:
    print 'Testing %s...' % (module_name,) ,
    sys.stdout.flush()
    try:
        test_mod = __import__(module_name, {}, {}, [None])
    except ImportError:
        print 'Failed to import test %r' % (module_name,)
        failed.append(module_name)
    else:
        try:
            test_mod.test()
        except (SystemExit, KeyboardInterrupt):
            raise
        except:
            sys.excepthook(*sys.exc_info())
            failed.append(module_name)
        else:
            print 'Succeeded.'

if failed:
    print 'Failures:', ', '.join(failed)
    sys.exit(1)
else:
    sys.exit(0)
