#!/usr/bin/env python

import cryptutil
import association
import storetest
import trustroot
import linkparse
import oidutil

cryptutil.test()
storetest.test()
trustroot.test()
linkparse.test()
oidutil.test()
association.test()
