#!/usr/bin/env python

import cryptutil
import association
import storetest
import trustroot
import linkparse
import oidutil
import kvform
import consumer
import fetchers

cryptutil.test()
storetest.test()
trustroot.test()
linkparse.test()
oidutil.test()
association.test()
kvform.test()
consumer.test()
fetchers.test()
