#!/bin/bash

rm -rf doc/*
epydoc --html --output doc/ --name "Python-OpenID" --top openid \
    --url "http://www.openidenabled.com/" --inheritance listed \
    --ignore-param-mismatch --no-private \
    openid/__init__.py \
    openid/dh.py \
    openid/association.py \
    openid/consumer/__init__.py \
    openid/consumer/consumer.py \
    openid/consumer/discover.py \
    openid/server/__init__.py \
    openid/server/server.py \
    openid/server/trustroot.py \
    openid/store/__init__.py \
    openid/store/interface.py \
    openid/store/filestore.py \
    openid/store/dumbstore.py \
    openid/store/sqlstore.py
